strategy:
  matrix:
    linux-cmcm:
      imageName: 'ubuntu-16.04'
      project: 'cmcm'
    linux-conan:
      imageName: 'ubuntu-16.04'
      project: 'conan'
    linux-vcpkg:
      imageName: 'ubuntu-16.04'
      project: 'vcpkg'
    mac-cmcm:
      imageName: 'macos-10.13'
      project: 'cmcm'
    mac-conan:
      imageName: 'macos-10.13'
      project: 'conan'
    mac-vcpkg:
      imageName: 'macos-10.13'
      project: 'vcpkg'
    windows-cmcm:
      imageName: 'vs2017-win2016'
      project: 'cmcm'
    windows-conan:
      imageName: 'vs2017-win2016'
      project: 'conan'
    windows-vcpkg:
      imageName: 'vs2017-win2016'
      project: 'vcpkg'

pool:
  vmImage: $(imageName)

steps:
- script: cmake .
  workingDirectory: $(project)
- script: cmake --build .
  workingDirectory: $(project)
