name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test ${{ matrix.PMM_tool }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        PMM_tool: ['cmcm', 'conan', 'vcpkg']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/setup-python@v1
      if: matrix.PMM_tool == 'conan' && matrix.os != 'macOS-latest'
      
    - name: Install python with brew
      run: brew install python
      if: matrix.PMM_tool == 'conan' && matrix.os == 'macOS-latest'

    - name: CMake
      working-directory:  ${{ matrix.PMM_tool }}
      run: cmake .
      
    - name: Build
      working-directory:  ${{ matrix.PMM_tool }}
      run: cmake --build .
        
